//
//  DeveloperPreview.swift
//  Airbnb
//
//  Created by Ziya Zaidov on 16.12.2023.
//

import Foundation

class DeveloperPreview {
    
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(features: [.selfCheckIn,.superHost],
              amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
              type: .villa,
              id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Alan Wayne",
              ownerImage: "male-profile-photo",
              numberOfBedroms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              imageURL: ["listing1","listing2","listing3","listing4","listing5","listing6","listing7","listing8","listing9","listing10"],
              price: 550,
              latitude: 25.7850,
              longitude: -80.1936,
              adress: "120 Main st",
              city: "Neapol",
              state: "Italy",
              title: "Island Villa",
              rating: 4.85),
        
            .init(features: [.selfCheckIn,.superHost],
                  amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
                  type: .villa,
                  id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "Ilon Mask",
                  ownerImage: "male-profile-photo",
                  numberOfBedroms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 6,
                  numberOfBeds: 6,
                  imageURL: ["listing1","listing2","listing3","listing4","listing5","listing6","listing7","listing8","listing9","listing10"],
                  price: 550,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  adress: "Central str 12",
                  city: "Los Angeles",
                  state: "california",
                  title: "California Villa",
                  rating: 4.85),
    
            .init(features: [.selfCheckIn,.superHost],
                  amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
                  type: .villa,
                  id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "John fgkgkfkgfk",
                  ownerImage: "male-profile-photo",
                  numberOfBedroms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  imageURL: ["listing4","listing2","listing3","listing1","listing5","listing6","listing7","listing8","listing9","listing10"],
                  price: 550,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  adress: "120 Main st",
                  city: "Miami",
                  state: "Florida",
                  title: "Baku Azebaijan",
                  rating: 4.85),
        
            .init(features: [.selfCheckIn,.superHost],
                  amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
                  type: .villa,
                  id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "John Smith",
                  ownerImage: "male-profile-photo",
                  numberOfBedroms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  imageURL: ["listing1","listing2","listing3","listing4","listing5","listing6","listing7","listing8","listing9","listing10"],
                  price: 550,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  adress: "120 Main st",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.85),
        
            .init(features: [.selfCheckIn,.superHost],
                  amenities: [.wifi,.alarmSystem,.balcony,.laundry,.tv],
                  type: .villa,
                  id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "John Smith",
                  ownerImage: "male-profile-photo",
                  numberOfBedroms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  imageURL: ["listing1","listing2","listing3","listing4","listing5","listing6","listing7","listing8","listing9","listing10"],
                  price: 550,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  adress: "120 Main st",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.85),
    ]
}
